In [2]:
import torch
from torch import nn

In [3]:
x=torch.randn(100,3)
layer=nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[ 0.1648,  0.1536,  0.0117],
        [-0.3313, -0.3490, -0.4192],
        [-0.4798, -0.5180, -0.4387],
        [ 0.3808, -0.3624, -0.5452],
        [ 0.0806,  0.3544, -0.3919]], requires_grad=True)
Parameter containing:
tensor([ 0.0345,  0.5412, -0.2346, -0.4627,  0.1987], requires_grad=True)


In [4]:
x=torch.randn(2,5)
layer=nn.ReLU()
print(layer(x))

tensor([[1.4683, 0.0000, 0.0000, 0.0000, 1.2957],
        [2.3218, 1.2983, 0.0000, 0.0000, 0.4977]])


In [5]:
x = torch.randn(3,7)
drop = nn.Dropout(p=0.3) # p는 죽일 확률
print(drop(x))

tensor([[-0.0000,  0.0755,  0.0000, -0.7607,  1.8829,  2.5939, -0.0000],
        [-0.6098,  0.9141, -0.0863, -0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.1868,  0.2729, -1.9359,  0.0000,  0.0000, -0.2259]])


In [6]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Linear(5,7),
                                      nn.Dropout(p=0.3))
                                      
    def forward(self, x):
        x = self.drop_layer(x)
        return x

model=sample_model()
model.train() # train mode로 전환
x=torch.randn(3,5) # 그 담에 x=torch.randn(2,3,5)
print(model(x))

model.eval()
print(model(x)) # test mode

tensor([[ 0.0000,  0.0000, -0.0000,  0.5969,  1.8511, -0.2778, -0.0000],
        [-0.4864, -1.6372,  1.2202, -0.3960, -0.3897, -0.2424, -0.0000],
        [-0.9845, -0.0000,  0.0000, -1.0859, -1.2159, -0.3908, -1.2975]],
       grad_fn=<MulBackward0>)
tensor([[ 0.4859,  1.2816, -0.1768,  0.4178,  1.2958, -0.1945, -0.0668],
        [-0.3405, -1.1460,  0.8541, -0.2772, -0.2728, -0.1697, -0.6837],
        [-0.6891, -1.6306,  1.2690, -0.7601, -0.8512, -0.2736, -0.9082]],
       grad_fn=<AddmmBackward0>)


In [7]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=1) # stride=1, padding=0 이 디폴트
layer(torch.randn(32,1,5,5)).shape
# nn.Linear(3,5) # 채채 # 얘는 채 또는 개채를 원함, 개 x 3
# nn.Conv2d(3,5) # 채채 # 얘는 채행열 또는 개채행열을 원함, 개 x 3 x 행 x 열

torch.Size([32, 2, 5, 5])

In [8]:
layer = nn.Conv2d(3,5,3, stride=2, padding=1)
print(layer(torch.randn(32,3,5,5)).shape)
print(layer.weight.shape)

torch.Size([32, 5, 3, 3])
torch.Size([5, 3, 3, 3])


In [9]:
conv1 = nn.Conv2d(1,8,6,stride=2)
x=torch.randn(32,1,28,28)
print(conv1(x).shape)

conv2 = nn.Conv2d(8,16,3,padding=1)
print(conv2(conv1(x)).shape)

Maxpool = nn.MaxPool2d(kernel_size=2, stride=(2,2))
print(Maxpool(conv2(conv1(x))).shape)

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [100]:
maxpool = nn.MaxPool2d(4) # 2 로만 줘도 자동 kernel_size=2, stride=(2,2)
x=torch.randn(1,1,8,8)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,8,8)).shape)

tensor([[[[ 0.8980,  1.2266,  1.4522,  1.2432, -0.4562, -0.8918, -0.4034,
           -1.4057],
          [ 0.4115,  0.1946,  0.9223, -1.4564,  1.0666,  0.6417,  0.7717,
           -0.9463],
          [ 0.7955,  2.1029, -0.5869, -0.8433,  0.1653,  0.8489, -0.7075,
           -0.3293],
          [-0.9108, -0.9058,  0.0160,  0.7648,  0.0086, -0.9517, -2.0725,
           -0.3827],
          [ 0.6649, -1.7719,  0.8154, -1.4079, -2.1974,  0.5078,  0.6951,
            0.1824],
          [ 0.0876,  0.9280, -1.5866,  0.5091,  1.1760,  1.3615,  0.6296,
           -0.7261],
          [ 0.5652, -1.7451,  0.4426,  1.6646,  0.4177,  0.1861, -1.4961,
            0.1226],
          [ 1.0260,  1.1399,  0.5152,  1.4978, -0.7679,  0.7840,  0.3065,
            0.0391]]]])
tensor([[[[2.1029, 1.0666],
          [1.6646, 1.3615]]]])
torch.Size([32, 3, 2, 2])


In [11]:
avgpool=nn.AvgPool2d(2)
x=torch.randn(1,1,6,6)
print(x)
print(avgpool(x))
print(avgpool(torch.randn(32,3,6,6)).shape)

tensor([[[[-1.5726,  0.8142,  0.3563,  1.2381, -0.6320, -1.3019],
          [ 0.1518, -2.0880, -0.7165,  0.0202,  1.1433, -0.7278],
          [ 0.1195, -0.6422, -0.9362,  1.1341,  1.3195, -0.2010],
          [-1.1519,  0.4506, -0.2712, -0.2922,  1.1258,  0.9489],
          [ 0.9435, -1.4890, -1.4196, -0.1235,  1.6557,  0.9055],
          [ 0.6604,  2.0383, -1.8690, -0.0621,  0.8644, -0.1596]]]])
tensor([[[[-0.6737,  0.2245, -0.3796],
          [-0.3060, -0.0914,  0.7983],
          [ 0.5383, -0.8686,  0.8165]]]])
torch.Size([32, 3, 3, 3])


In [12]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6,stride=2)
        self.conv2 = nn.Conv2d(8,16,3,padding=1)
        self.Maxpool2 = nn.MaxPool2d(2)
        self.fc = nn.Linear(16*6*6,10)

    def forward(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool2(x)
        # x = torch.flatten(x, start_dim=1)
        # x = self.fc(x)
        return x

x = torch.randn(32,1,28,28)
model = CNN()
print(model(x).shape)

torch.Size([32, 16, 6, 6])


## .parameters() vs .modules() vs .children() 그리고 isinstance의 활용

In [13]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x
        
model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [15]:
model.parameters()

<generator object Module.parameters at 0x7f141bb95f90>

In [17]:
list(model.parameters())[0]
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

Parameter containing:
tensor([[-0.0134, -0.2526],
        [-0.6953,  0.6233],
        [-0.0113,  0.6361]], requires_grad=True)

In [58]:
# for tranfer learning
model=MLP()
print([p for p in model.parameters() if p.requires_grad])

for p in model.parameters(): # 전체 freeze
    p.requires_grad=False
model.fc_out = nn.Linear(4,10)

params = [p for p in model.parameters() if p.requires_grad]
print(params)

from torch import optim
optimizer = optim.Adam(params, lr=0.1)

[Parameter containing:
tensor([[ 0.1996,  0.1994],
        [ 0.3444, -0.4502],
        [ 0.4380, -0.6523]], requires_grad=True), Parameter containing:
tensor([-0.5272,  0.6027, -0.4804], requires_grad=True), Parameter containing:
tensor([[ 0.4240, -0.4905, -0.5493],
        [ 0.4089, -0.3101, -0.2805],
        [ 0.1004,  0.1807, -0.1730],
        [-0.0322,  0.5067, -0.2101]], requires_grad=True), Parameter containing:
tensor([-0.2618,  0.3359, -0.0152, -0.5487], requires_grad=True), Parameter containing:
tensor([[-0.4201,  0.2369, -0.3969, -0.3237]], requires_grad=True), Parameter containing:
tensor([0.4398], requires_grad=True)]
[Parameter containing:
tensor([[-0.3634,  0.3684, -0.3112, -0.0318],
        [ 0.1439, -0.1164,  0.4683, -0.0255],
        [-0.0229, -0.4852,  0.4611, -0.3768],
        [ 0.2551, -0.3565,  0.4436, -0.1739],
        [ 0.1431, -0.4204, -0.1562,  0.1049],
        [ 0.3607,  0.1683, -0.1850,  0.4222],
        [ 0.4475,  0.0755, -0.4214, -0.0474],
        [ 0.0622,

In [59]:
list(model.named_parameters())[0]
# [('layer0.weight', weight 값), ('layer0.bias', bias 값), ('layer1.weight', weight 값), ('layer1.bias', bias 값), ...]

('fc1.0.weight', Parameter containing:
 tensor([[ 0.1996,  0.1994],
         [ 0.3444, -0.4502],
         [ 0.4380, -0.6523]]))

In [60]:
for name, p in model.named_parameters():
    print(name)
    print(p)

fc1.0.weight
Parameter containing:
tensor([[ 0.1996,  0.1994],
        [ 0.3444, -0.4502],
        [ 0.4380, -0.6523]])
fc1.0.bias
Parameter containing:
tensor([-0.5272,  0.6027, -0.4804])
fc2.0.weight
Parameter containing:
tensor([[ 0.4240, -0.4905, -0.5493],
        [ 0.4089, -0.3101, -0.2805],
        [ 0.1004,  0.1807, -0.1730],
        [-0.0322,  0.5067, -0.2101]])
fc2.0.bias
Parameter containing:
tensor([-0.2618,  0.3359, -0.0152, -0.5487])
fc_out.weight
Parameter containing:
tensor([[-0.3634,  0.3684, -0.3112, -0.0318],
        [ 0.1439, -0.1164,  0.4683, -0.0255],
        [-0.0229, -0.4852,  0.4611, -0.3768],
        [ 0.2551, -0.3565,  0.4436, -0.1739],
        [ 0.1431, -0.4204, -0.1562,  0.1049],
        [ 0.3607,  0.1683, -0.1850,  0.4222],
        [ 0.4475,  0.0755, -0.4214, -0.0474],
        [ 0.0622, -0.1349, -0.1851,  0.2030],
        [ 0.3657,  0.3324, -0.2247,  0.2239],
        [-0.0134, -0.4485, -0.1851, -0.4764]], requires_grad=True)
fc_out.bias
Parameter containing

In [61]:
model.modules()

<generator object Module.modules at 0x7f141b78bdd0>

In [62]:
list(model.modules())

[MLP(
   (fc1): Sequential(
     (0): Linear(in_features=2, out_features=3, bias=True)
     (1): ReLU()
   )
   (fc2): Sequential(
     (0): Linear(in_features=3, out_features=4, bias=True)
     (1): ReLU()
   )
   (fc_out): Linear(in_features=4, out_features=10, bias=True)
 ), Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ), Linear(in_features=2, out_features=3, bias=True), ReLU(), Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ), Linear(in_features=3, out_features=4, bias=True), ReLU(), Linear(in_features=4, out_features=10, bias=True)]

In [63]:
print([m for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight.grad for m in model.modules() if isinstance(m,nn.Linear)])

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]
[Parameter containing:
tensor([[ 0.1996,  0.1994],
        [ 0.3444, -0.4502],
        [ 0.4380, -0.6523]]), Parameter containing:
tensor([[ 0.4240, -0.4905, -0.5493],
        [ 0.4089, -0.3101, -0.2805],
        [ 0.1004,  0.1807, -0.1730],
        [-0.0322,  0.5067, -0.2101]]), Parameter containing:
tensor([[-0.3634,  0.3684, -0.3112, -0.0318],
        [ 0.1439, -0.1164,  0.4683, -0.0255],
        [-0.0229, -0.4852,  0.4611, -0.3768],
        [ 0.2551, -0.3565,  0.4436, -0.1739],
        [ 0.1431, -0.4204, -0.1562,  0.1049],
        [ 0.3607,  0.1683, -0.1850,  0.4222],
        [ 0.4475,  0.0755, -0.4214, -0.0474],
        [ 0.0622, -0.1349, -0.1851,  0.2030],
        [ 0.3657,  0.3324, -0.2247,  0.2239],
        [-0.0134, -0.4485, -0.1851, -0.4764]], requires_grad=True)]
[None, None, None]


In [64]:
# weight initialization에 활용
for m in model.modules():
    if isinstance(m, nn.Linear):
        nn.init.kaiming_normal_(m.weight)
        # nn.init.constant_(m.weight, 1)

print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])

[Parameter containing:
tensor([[ 0.8947, -1.2693],
        [ 0.5346,  1.6689],
        [-0.0714,  1.6138]]), Parameter containing:
tensor([[-0.2995,  0.8541,  0.0983],
        [ 1.1411,  0.8850,  1.8759],
        [-0.3607, -0.4720,  0.0356],
        [-0.9508, -1.0568, -0.1150]]), Parameter containing:
tensor([[ 1.0350, -0.1308,  0.3618,  0.8463],
        [-1.0730,  0.9058, -0.5026, -0.4163],
        [ 0.1431,  0.7085, -0.4777,  0.3908],
        [ 0.2633,  0.0488, -0.0305, -0.0534],
        [-0.3727,  0.8493, -0.8423, -0.4329],
        [ 0.0821,  1.9561,  0.3025, -1.2846],
        [-0.1071, -1.0848,  0.5324,  1.6751],
        [-0.4850,  0.6923,  1.1755, -0.3045],
        [-0.3548, -0.0378,  1.3580,  0.5613],
        [ 1.5403,  0.2447,  2.2214,  0.1515]], requires_grad=True)]


In [65]:
model.children()

<generator object Module.children at 0x7f141b78bf90>

In [66]:
list(model.children())

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ), Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ), Linear(in_features=4, out_features=10, bias=True)]

In [67]:
x = torch.randn(2,2)
list(model.children())[0](x)

tensor([[0.0000, 0.6386, 0.0000],
        [0.0000, 0.7796, 0.0000]])

In [68]:
print(*list(model.children())[:2])
sub_network = nn.Sequential(*list(model.children())[:2])
print(sub_network)
print(sub_network(x))

Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
) Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): ReLU()
)
Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)
tensor([[0.2836, 0.9011, 0.0000, 0.0000],
        [0.4041, 1.0259, 0.0000, 0.0000]])


## ModuleList vs Sequential

In [81]:
fc=nn.Linear(3,3)
layer_list = [fc for _ in range(5)]
layers1 = nn.Sequential(*layer_list)
layers2 = nn.ModuleList(layer_list)
print(layers1)
print(layers2)

x=torch.randn(1,3)
print(layers1(x))

# print(layers2(x)) # error!
for layer in layers2:
    x = layer(x)
print(x)

Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
tensor([[ 0.5768,  0.6888, -0.4326]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5768,  0.6888, -0.4326]], grad_fn=<AddmmBackward0>)


In [92]:
# 걍 리스트 쓰지 왜 nn.ModuleList 를 쓸까?
class testNet(nn.Module):
    def __init__(self):
        super().__init__()

        # self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)]
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])

    def forward(self,x):
        for layer in self.Module_List:
            x = layer(x)
        return x

model=testNet()
print(model(torch.randn(1,3)))

print(model) # 그냥 리스트로 하면 등록이 안돼있다!

optimizer = optim.Adam(model.parameters(), lr = 0.1) # 등록이 안돼있으면 parameter를 못 찾는다!

tensor([[ 0.8610, -0.0682, -0.5883]], grad_fn=<AddmmBackward0>)
testNet(
  (Module_List): ModuleList(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): Linear(in_features=3, out_features=3, bias=True)
  )
)


In [99]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y):
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

block = small_block()
print(block)
model = nn.Sequential(block, block)
print(model)
# model(torch.randn(1), torch.randn(1)) # error!
# nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안된다!!

model = nn.ModuleList([block,block])
x = torch.randn(1)
y = torch.randn(1)
for block in model:
    x, y = block(x,y)
print(x, y)

small_block(
  (block_x): Linear(in_features=1, out_features=1, bias=True)
  (block_y): Linear(in_features=1, out_features=1, bias=True)
)
Sequential(
  (0): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
  (1): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
)
tensor([-0.0330], grad_fn=<AddBackward0>) tensor([0.4277], grad_fn=<AddBackward0>)
