## numpy와 닮은 파이토치(pytorch)

In [2]:
import torch
a=torch.tensor([1,2,3,4])
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=torch.tensor([1,2,3.1,4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

/opt/anaconda3/envs/test/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([1, 2, 3, 4])
<class 'torch.Tensor'>
torch.int64
torch.Size([4])
torch.float32
tensor([1.0000, 2.0000, 3.1000, 4.0000])


In [3]:
A=torch.tensor([[1,2,3],[3,4,5]]) # 이 셀부터는 import numpy as torch 는 실행 했다 치고 작성
A=torch.tensor([[1,2],[4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.numel()) # 전체 성분의 수

tensor([[1, 2],
        [4, 5]])
torch.Size([2, 2])
2
4


In [4]:
print(torch.zeros(5))
print(torch.zeros_like(A))
print(torch.ones(5))
print(torch.zeros( (3,3) ))
print(torch.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(torch.arange(0,1,0.1)) # 소수점 가능
print(torch.linspace(0,1,10,)) # 0 에서부터 1 포함(default) 10개로

tensor([0., 0., 0., 0., 0.])
tensor([[0, 0],
        [0, 0]])
tensor([1., 1., 1., 1., 1.])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([3, 5, 7, 9])
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])


In [5]:
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
c=a+b
print(c) # 드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴!

tensor([5, 7, 9])


In [6]:
A=torch.tensor([[1,2,3],[1,2,3]])
B=torch.tensor([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C) 
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

tensor([[5, 7, 9],
        [2, 3, 4]])
tensor([[-3, -3, -3],
        [ 0,  1,  2]])

tensor([[ 4, 10, 18],
        [ 1,  2,  3]])
tensor([[0.2500, 0.4000, 0.5000],
        [1.0000, 2.0000, 3.0000]])
tensor([[16, 25, 36],
        [ 1,  1,  1]])


In [7]:
A=torch.tensor([[1,2],[3,4]])
B=torch.tensor([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

tensor([[ 1,  4],
        [ 9, 16]])
tensor([[ 7, 10],
        [15, 22]])


## pytorch의 인덱싱 슬라이스

In [8]:
a=torch.tensor([1,2,3,4,5,6,7,8,9]) 
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0]) 
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

tensor(1)
tensor(2)
tensor(9)
tensor([2, 3, 4])
tensor([8, 9])
tensor([1, 2, 3, 4, 5, 6, 7])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [9]:
# 행렬에 대한 인덱싱과 슬라이싱
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열
print(A[:][2])

tensor([1, 2, 3])
tensor([7, 8, 9])
tensor([[4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(3)
tensor(3)
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
tensor([4, 5, 6])
tensor([4, 6])
tensor([3, 6, 9])
tensor([7, 8, 9])


In [10]:
# 3차원 행렬 인덱싱
A=torch.tensor([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,   
                [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(A[0,1,2])

a=torch.tensor([[[1,2,3,4]]])
print(a.shape)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
torch.Size([2, 3, 4])
tensor(6)
torch.Size([1, 1, 4])


In [4]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=torch.tensor([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A==3] = 100
print(A) # 그러면 이런 것도 가능하다! (3과 같은 애를 100으로 바꿔줘)

A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
B=torch.tensor([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=torch.tensor([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
tensor([[False, False,  True, False],
        [False,  True, False,  True]])
tensor([3, 3, 3])
tensor([[  1,   2, 100,   4],
        [  5, 100,   7, 100]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2],
        [7, 8]])
tensor([1, 2])


In [5]:
# torch로 인덱싱
a=torch.tensor([1,2,3,4,5])
A=a[2]
print(A)
A=a[ torch.tensor(2) ] # torch.tensor를 안에다가?
print(A)
A=a[ torch.tensor([2,3,4]) ]
print(A)
A=a[ torch.tensor([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=torch.tensor([[1,2,3],[4,5,6]])
print(a[0])
A=a[ torch.tensor([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = tensor([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

tensor(3)
tensor(3)
tensor([3, 4, 5])
tensor([[3, 3, 3],
        [4, 4, 4]])
tensor([1, 2, 3])
torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[4, 5, 6],
         [4, 5, 6]]])


In [14]:
A=torch.tensor([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ tensor(bool) ] => A와 같은 shape을 가지는 array형 bool이 어디에 True를 가지고 있냐
print(A[ torch.tensor([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,False], [False,True] ])
# 4. A[ tensor ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ torch.tensor([1,1,2,2,2]) ])


a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a[:,2])
print(a[2])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
torch.Size([4, 2])
tensor(2)
tensor([2])
tensor([2])
tensor([2])
tensor([[3, 4],
        [3, 4],
        [5, 6],
        [5, 6],
        [5, 6]])
tensor([3, 6, 9])
tensor([7, 8, 9])


## pytorch의 여러 함수들

In [17]:
A=torch.randn(3,3) # Normal의 n 평균0 분산1
B=torch.rand(3,3) # 이건 uniform 0~1사이
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들

tensor([[ 1.3847,  0.9757, -0.7290],
        [-0.5492,  0.5003,  0.3300],
        [-0.0984, -1.5610, -0.0483]])
tensor([[0.9067, 0.3553, 0.9608],
        [0.1306, 0.5061, 0.5710],
        [0.3285, 0.7662, 0.9712]])
tensor([[-0.5492,  0.5003,  0.3300],
        [-0.0984, -1.5610, -0.0483]])


In [26]:
A=torch.randn(3,3)
print(A)
print(torch.abs(A))
print(torch.sqrt(torch.abs(A)))
print(torch.exp(A))
print(torch.log(torch.abs(A)))
print(torch.log(torch.exp(torch.tensor(1)))) # torch.exp(torch.tensor(1)) = e^1
print(torch.log10(torch.tensor(10)))
print(torch.log2(torch.tensor(2)))
print(torch.round(A)) # 반올림
print(torch.round(A,decimals=2)) # 소수점 둘째자리까지
print(torch.floor(A)) # 내림
print(torch.ceil(A)) # 올림

tensor([[-8.7583e-01, -3.7423e-02,  1.7002e+00],
        [ 5.2032e-01, -1.6655e+00, -9.7117e-01],
        [ 1.1938e+00, -4.3754e-01, -2.4878e-04]])
tensor([[8.7583e-01, 3.7423e-02, 1.7002e+00],
        [5.2032e-01, 1.6655e+00, 9.7117e-01],
        [1.1938e+00, 4.3754e-01, 2.4878e-04]])
tensor([[0.9359, 0.1934, 1.3039],
        [0.7213, 1.2905, 0.9855],
        [1.0926, 0.6615, 0.0158]])
tensor([[0.4165, 0.9633, 5.4750],
        [1.6826, 0.1891, 0.3786],
        [3.2997, 0.6456, 0.9998]])
tensor([[-0.1326, -3.2855,  0.5307],
        [-0.6533,  0.5101, -0.0293],
        [ 0.1772, -0.8266, -8.2990]])
tensor(1.0000)
tensor(1.)
tensor(1.)
tensor([[-1., -0.,  2.],
        [ 1., -2., -1.],
        [ 1., -0., -0.]])
tensor([[-0.8800, -0.0400,  1.7000],
        [ 0.5200, -1.6700, -0.9700],
        [ 1.1900, -0.4400, -0.0000]])
tensor([[-1., -1.,  1.],
        [ 0., -2., -1.],
        [ 1., -1., -1.]])
tensor([[-0., -0.,  2.],
        [ 1., -1., -0.],
        [ 2., -0., -0.]])


In [29]:
print(torch.sin(torch.tensor(torch.pi/6)))
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


In [34]:
torch.nan # not a number
print(torch.log(torch.tensor(-1)))
print(torch.isnan(torch.tensor([1,2,torch.nan,3,4]))) # nan이 들어있는지 확인
print(torch.isinf(torch.tensor([1,2,3,4,torch.inf]))) # 무한대값이 있는지 확인

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [47]:
A=torch.randn(3,4)
print(A)
print(torch.max(A))
print(torch.max(A,dim=0))
print(torch.max(A,dim=1)) # 1D tensor로 바꿔버림
print(torch.max(A,dim=0,keepdim=True))
print(torch.max(A,dim=1,keepdim=True))
print(torch.min(A))
print(torch.min(A,dim=0))
print(torch.min(A,dim=1))
print(torch.argmax(A)) # argmax => 
print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

tensor([[ 0.3195, -0.1947, -2.9626,  1.0000],
        [ 0.4767,  1.1473, -0.7782, -0.8425],
        [ 1.8241, -0.8031,  0.1269, -1.0050]])
tensor(1.8241)
torch.return_types.max(
values=tensor([1.8241, 1.1473, 0.1269, 1.0000]),
indices=tensor([2, 1, 2, 0]))
torch.return_types.max(
values=tensor([1.0000, 1.1473, 1.8241]),
indices=tensor([3, 1, 0]))
torch.return_types.max(
values=tensor([[1.8241, 1.1473, 0.1269, 1.0000]]),
indices=tensor([[2, 1, 2, 0]]))
torch.return_types.max(
values=tensor([[1.0000],
        [1.1473],
        [1.8241]]),
indices=tensor([[3],
        [1],
        [0]]))
tensor(-2.9626)
torch.return_types.min(
values=tensor([ 0.3195, -0.8031, -2.9626, -1.0050]),
indices=tensor([0, 2, 0, 2]))
torch.return_types.min(
values=tensor([-2.9626, -0.8425, -1.0050]),
indices=tensor([2, 3, 3]))
tensor(8)
tensor([2, 1, 2, 0])
tensor([3, 1, 0])


In [46]:
a=torch.randn(6,1)
print(a)
a_sorted=torch.sort(a,dim=0)
print(a_sorted)

b=torch.randn(6,1)
print(b)
b_sorted=torch.sort(b,dim=0,descending=True)
print(b_sorted)
print(b.abs())

tensor([[ 0.0555],
        [-0.3372],
        [ 1.1622],
        [-0.0963],
        [ 1.1899],
        [-0.4884]])
torch.return_types.sort(
values=tensor([[-0.4884],
        [-0.3372],
        [-0.0963],
        [ 0.0555],
        [ 1.1622],
        [ 1.1899]]),
indices=tensor([[5],
        [1],
        [3],
        [0],
        [2],
        [4]]))
tensor([[-0.5910],
        [-0.3695],
        [-0.0761],
        [ 1.4296],
        [-0.1417],
        [-1.6219]])
torch.return_types.sort(
values=tensor([[ 1.4296],
        [-0.0761],
        [-0.1417],
        [-0.3695],
        [-0.5910],
        [-1.6219]]),
indices=tensor([[3],
        [2],
        [4],
        [1],
        [0],
        [5]]))
tensor([[0.5910],
        [0.3695],
        [0.0761],
        [1.4296],
        [0.1417],
        [1.6219]])


In [48]:
A=torch.randn(3,4)
print(A)
print(torch.sum(A))
print(torch.sum(A,dim=1))
print(torch.sum(A,dim=1,keepdims=True))
print(torch.mean(A))
print(torch.mean(A,dim=1))
print(torch.mean(A,dim=1,keepdims=True))
print(torch.std(A)) # standard deviation 표준 편차

print(A.sum(dim=1, keepdims=True))
print(A.mean(dim=1, keepdims=True))
print(A.std())

tensor([[-1.2947, -0.8835, -0.3740,  0.3263],
        [ 0.9863, -1.4937,  0.5735, -1.3775],
        [-0.1114,  0.4053, -0.0176,  0.3256]])
tensor(-2.9355)
tensor([-2.2259, -1.3114,  0.6018])
tensor([[-2.2259],
        [-1.3114],
        [ 0.6018]])
tensor(-0.2446)
tensor([-0.5565, -0.3278,  0.1505])
tensor([[-0.5565],
        [-0.3278],
        [ 0.1505]])
tensor(0.8366)
tensor([[-2.2259],
        [-1.3114],
        [ 0.6018]])
tensor([[-0.5565],
        [-0.3278],
        [ 0.1505]])
tensor(0.8366)


In [49]:
A=torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

tensor([4, 4, 4, 2, 1, 3, 3, 4, 1, 1, 3, 3])
torch.Size([12])
tensor([[[4, 4, 4],
         [2, 1, 3]],

        [[3, 4, 1],
         [1, 3, 3]]])
3


In [56]:
a=torch.tensor([1,2,3])
b=torch.tensor([2,2,1])
print(torch.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose(1,0)@b)
print(a.permute(1,0)@b) # 3차원 이상일 때
print(a.T@b)


A=torch.randn(4,3,6)
print(A.permute(0,2,1).shape)
print(A.transpose(0,2).shape) # transpose는 둘끼리 자리 바꾸기만 가능

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([6, 3, 4])


In [57]:
A=torch.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [62]:
x=torch.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape) 
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [73]:
A=torch.ones((2,3,4))
B=torch.zeros((2,3,4))
#C=torch.vstack([A,B]) # 헷갈려서 잘 안씀
#D=torch.hstack([A,B]) # 이놈도 마찬가지
E=torch.cat([A,B],dim=0)
F=torch.cat([A,B],dim=1)
G=torch.cat([A,B],dim=2)

print(C)
print(D)
print(E)
print(F)
print(G)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([

In [76]:
A = torch.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)


torch.Size([1, 1, 1, 3, 1, 1, 4, 1])
torch.Size([3, 4])


In [81]:
A = torch.randn(3,4)
print(A.unsqueeze(dim=0).shape)
print(A.unsqueeze(dim=1).shape)
print(A.unsqueeze(dim=0).shape)
print(A.reshape(1,3,4).shape)
print(A.reshape(3,1,4).shape)
print(A.reshape(3,4,1).shape)

torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([1, 3, 4])
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [82]:
A=torch.ones(3,4)
B=torch.zeros(3,4)
A=A.unsqueeze(dim=0)
B=B.unsqueeze(dim=0)
C=torch.cat([A,B], dim=0)
print(C)
print(C.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])


In [85]:
A=torch.tensor([[1,2],[3,4]])
B=A.clone()
B[0,0]=100

print(B)
print(A)


tensor([[100,   2],
        [  3,   4]])
tensor([[1, 2],
        [3, 4]])


## @에 대해 좀만 더
@JinDDory

In [86]:
A=torch.randn(5,7)
B=torch.randn(7,10)
C=A@B
print(C.shape)

A=torch.randn(32,5,7)
B=torch.randn(32,7,10)
C=A@B
print(C.shape)

torch.Size([5, 10])
torch.Size([32, 5, 10])


In [90]:
A=torch.randn(32,5,7)
B=torch.randn(7,10)

C=A@B.repeat(32,1,1) # (7,10)짜리가 32,7,10이 됨
D=A@B

print(C.shape)
print(D.shape)
print((C-D).abs().max())

torch.Size([32, 5, 10])
torch.Size([32, 5, 10])
tensor(4.7684e-07)


In [91]:
A = torch.rand(2,3)
A_repeat=A.repeat(3,1,3,2)
print(A)
print(A_repeat)
print(A_repeat.shape)


tensor([[0.0495, 0.8768, 0.6049],
        [0.0132, 0.5091, 0.0374]])
tensor([[[[0.0495, 0.8768, 0.6049, 0.0495, 0.8768, 0.6049],
          [0.0132, 0.5091, 0.0374, 0.0132, 0.5091, 0.0374],
          [0.0495, 0.8768, 0.6049, 0.0495, 0.8768, 0.6049],
          [0.0132, 0.5091, 0.0374, 0.0132, 0.5091, 0.0374],
          [0.0495, 0.8768, 0.6049, 0.0495, 0.8768, 0.6049],
          [0.0132, 0.5091, 0.0374, 0.0132, 0.5091, 0.0374]]],


        [[[0.0495, 0.8768, 0.6049, 0.0495, 0.8768, 0.6049],
          [0.0132, 0.5091, 0.0374, 0.0132, 0.5091, 0.0374],
          [0.0495, 0.8768, 0.6049, 0.0495, 0.8768, 0.6049],
          [0.0132, 0.5091, 0.0374, 0.0132, 0.5091, 0.0374],
          [0.0495, 0.8768, 0.6049, 0.0495, 0.8768, 0.6049],
          [0.0132, 0.5091, 0.0374, 0.0132, 0.5091, 0.0374]]],


        [[[0.0495, 0.8768, 0.6049, 0.0495, 0.8768, 0.6049],
          [0.0132, 0.5091, 0.0374, 0.0132, 0.5091, 0.0374],
          [0.0495, 0.8768, 0.6049, 0.0495, 0.8768, 0.6049],
          [0.0132, 0.50

## numpy <-> torch 왔다갔다 가능

In [2]:
import numpy as np
import torch

a=np.array([1,2,3])
b=torch.tensor([1,2,3])

A=torch.from_numpy(a)
B=b.numpy()
print(type(A))
print(type(B))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


## 딥러닝을 가능케한 autograd

In [97]:
x=torch.tensor([1.], requires_grad=True) #float이어야해서 1.
print(x)

tensor([1.], requires_grad=True)


In [104]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
print(y) # PowBackward0가 붙어있다!
print(x.grad)
y.backward()
print(x.grad)# y=x**2을 미분한 2x의 x 값에 1을 대입한 gradient 값

tensor([1.], grad_fn=<PowBackward0>)
None
tensor([2.])


In [109]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
print(y)
# y.retain_grad()
z = 3*y
print(z)#MulBackward0가 붙어있다!

z.backward()
print(x.grad)#chain rule로 알아냄
print(y.grad)#warning! 중간건 안된다 but, 위에 retain_grad()로 알 수 있음


tensor([1.], grad_fn=<PowBackward0>)
tensor([3.], grad_fn=<MulBackward0>)
tensor([6.])
tensor([3.])


In [115]:
x=torch.tensor([1.], requires_grad=True)
y=x**2
z = 3*y

y.backward()
print(x.grad)

tensor([2.])


In [119]:
x=torch.tensor([2.], requires_grad=True)
a=x**2
b=a+1
print(b) # AddBackward0가 붙어있다
c=b**2
c.backward()
print(x.grad)


tensor([5.], grad_fn=<AddBackward0>)
tensor([40.])


In [121]:
x=torch.tensor([1., 2., 3.] ,requires_grad=True)
y=torch.sum(x**2) # x1**2 + x2**2 + x3**2
y.backward()

print(y)
print(x.grad) # 스칼라를 벡터로 미분

tensor(14., grad_fn=<SumBackward0>)
tensor([2., 4., 6.])


In [124]:
x=torch.tensor([1.] ,requires_grad=True)
x.requires_grad=False
# tranfer learning 할 때 필요
y=x**2
print(y)
# y.backward() # error!

tensor([1.])


In [125]:
x=torch.tensor([1.] ,requires_grad=True)
x=x.detach() #detach도 많이 쓰는듯
print(x)
y=x**2
print(y)
# y.backward() # error!

tensor([1.])
tensor([1.])


In [129]:
# detach 와 torch.no_grad
x=torch.tensor([1.], requires_grad=True)
# chain rule을 위해 계속 grad_fu을 update 하니까 grad_fn 잠시 안 계산하고 싶을 때 torch.no_grad
# 모델 테스트 시에는 불필요하게 메모리 쓸 필요 없기 때문!
with torch.no_grad():
    y=x**2
    print(x.requires_grad)
    print(y)
print(x.requires_grad)
# y.backward() # error!
y=x**2
print(y)

x=torch.tensor([1.], requires_grad=True)
x=x.detach()
y = x**2
print(x.requires_grad)
print(y)# y.backward() # error!

True
tensor([1.])
True
tensor([1.], grad_fn=<PowBackward0>)
False
tensor([1.])


In [ ]:
# from torchviz import make_dot
x=torch.tensor([1., 2.],requires_grad=True)
# make_dot(x)
# make_dot(x**2)
# make_dot(x**2+1)
make_dot((x**2+1)**2)

## 간단한 인공신경망 만들기
